Temporarily disable our use of _, since we're not currently using it, and it is causing problems in production:
  File "/usr/lib/python2.4/site-packages/turbogears/util.py", line 159, in get_project_meta
      for dirname in os.listdir("./"):
  OSError: [Errno 13] Permission denied: './'