Revert "Disable bugzilla multicall by default, which should hopefully fix #254"
This reverts commit 88bb79f48463a82b48faf6442020ae855f1d4c62.

This change caused the following exception in production:

  File "/usr/lib/python2.4/site-packages/bodhi/model.py", line 895, in fetch_details
    if bug.product == 'Security Response':
  File "/usr/lib/python2.4/site-packages/bugzilla/base.py", line 1104, in __getattr__
    raise AttributeError, "field %s not in bugzilla.bugfields" % name
  AttributeError: field product not in bugzilla.bugfields