Prettify an error message
When submitting a buildroot override for a build which is already in
another buidroot override, the user gets the following message:

  Error: buildroot override for u'php-5.4.7-1.fc17' already exists

The u'...' is quite ugly, and it is trivial to remove it.